full_work_app/full_work_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from restaurants.views import (
    RestaurantListview,
    RestaurantDetailedView,
    RestaurantCreateView )


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^menus/', include('menus.urls',namespace='menus')),
    url(r'^About/$',TemplateView.as_view(template_name='About.html'),name='about'),
    url(r'^Contact/$',TemplateView.as_view(template_name='contact.html'),name='contact'),
    url(r'^login/$',LoginView.as_view(),name='login')


]

full_work_app/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemCreateView,
    ItemUpdateView,
    ItemDetailView,


)

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(),name='create'),
    # url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
    url(r'^$', ItemListView.as_view(),name='list'),
   ]

full_work_app/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

full_work_app/templates/snippets/form_snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form METHOD="POST"> {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>

{% if form.instance %}
<h1>{{ form.instance.name }}</h1>
{% endif %}

full_work_app/templates/snippets/js.html
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>

full_work_app/templates/snippets/nav.html
<div class='container'>

<a href='{% url "home" %}'>Home</a>
<a href='{% url "about" %}'>About</a>
<a href='{% url "contact" %}'>contact</a>
    {% if request.user.is_authenticated %}
    <a href='{% url "restaurants:list" %}'>Restaurants</a>
    <a href='{% url "menus:list" %}'>Menu Items</a>
    {% endif %}
</div>

full_work_app/templates/snippets/sidebar.html
<ul>
    <li>Item1</li>
    <li>Item2</li>
    <li>Item3</li>

</ul>