full_work_app/full_work_app/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from restaurants.views import (
    RestaurantListview,
    RestaurantDetailedView,
    RestaurantCreateView )


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',TemplateView.as_view(template_name='home.html'),name='home'),
    url(r'^restaurants/', include('restaurants.urls',namespace='restaurants')),
    url(r'^u/', include('profiles.urls',namespace='profiles')),
    url(r'^menus/', include('menus.urls',namespace='menus')),
    url(r'^About/$',TemplateView.as_view(template_name='About.html'),name='about'),
    url(r'^Contact/$',TemplateView.as_view(template_name='contact.html'),name='contact'),
    url(r'^login/$',LoginView.as_view(),name='login')


]

full_work_app/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemCreateView,
    ItemUpdateView,
    ItemDetailView,


)

urlpatterns = [

    url(r'^create/$', ItemCreateView.as_view(),name='create'),
    # url(r'^(?P<pk>\d+)/edit/$',ItemUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/$',ItemUpdateView.as_view(),name='detail'),
    url(r'^$', ItemListView.as_view(),name='list'),
   ]

full_work_app/menus/models.py
from django.conf import settings
from django.db import models

from restaurants.models import RestaurantLocation
from  django.core.urlresolvers import reverse

# Create your models here.
class Item(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(RestaurantLocation)
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text="Seperate each item by comma ")
    excludes    = models.TextField(blank=True,null=True,help_text="Seperate each item by comma ")
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('menus:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-updated','-timestamp']


    def get_contents(self):
        return self.contents.split(',')

    def get_excludes(self):
        return self.excludes.split(',')

full_work_app/menus/forms.py
from django import forms


from .models import Item

from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    def __init__(self,user=None,*args,**kwargs):
        print(user)
        super(ItemForm,self).__init__(*args,**kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

full_work_app/menus/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from .models import Item
from .forms import ItemForm
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class ItemListView(ListView):
    template_name = 'menus/item_list.html'
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin,CreateView):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView,self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView,self ).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context



class ItemUpdateView(LoginRequiredMixin,UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemUpdateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

full_work_app/menus/templates/menus/detail-update.html
{% extends "base.html" %}
{% block head_title %}{{ form.instance.name }}Menu Items | {{block.super}}{% endblock head_title %}
{% block content %}
<h1> {{ form.instance.name }} </h1>
<p>Location: {{ form.instance.name }} </p>
        {% if form.instance.contents %}
        Contents
        <ul>
            {% for item in form.instance.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if form.instance.excludes %}
        Excludes
        <ul>
            {% for item in form.instance.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

</ul>

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form_snippet.html' with form=form %}
{% endblock %}

full_work_app/menus/templates/menus/item_detail.html
{% extends "base.html" %}
{% block head_title %}Menu Items | {{block.super}}{% endblock head_title %}
{% block content %}
<h1> {{ object.name }} </h1>
<p>Location: {{ object.restaurant.name }} </p>
        {% if object.contents %}
        Contents
        <ul>
            {% for item in object.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if object.excludes %}
        Excludes
        <ul>
            {% for item in object.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

</ul>
{% endblock %}

full_work_app/menus/templates/menus/item_list.html
{% extends "base.html" %}
{% block head_title %}Menu Items | {{block.super}}{% endblock head_title %}
{% block content %}
<h1>Menu Items <small><a href="{% url "menus:create" %}">Add</a></small> </h1>

<ul>
    {% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a></br>
        {% if obj.contents %}
        Contents
        <ul>
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if obj.excludes %}
        Excludes
        <ul>
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

    </li>
    {% endfor %}

</ul>
{% endblock %}